spring.application.name=studentrecord

spring.data.mongodb.uri=mongodb://localhost:27017/studentrecord

jwt.secret=c3R1ZGVudC1yZWNvcmRzLWp3dC1zZWNyZXQtMjAyNi1zYWZlLWtleQ==
jwt.expiration-ms=3600000

server.port=8080